spring:
  application:
    name: products-server
  jpa:
    hibernate:
      ddl-auto: update
    #database: mysql
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
      
    
#eureka:
 # client:
  #  fetch-registry: true
   # register-with-eureka: true
    #service-url:
     # defaultZone: ${SERVICE_DISCOVERY_ADDRESS}